### ISSUE TITLE
Consider archiving project?

### ISSUE THREAD

**Issue by frankinspace** [KMarkert/simple-cmr#1]
Hello, I notice this package has not been updated for a few years. There is some active development happening on the https://github.com/nasa/python_cmr library which seems to overlap with the intent of this repository. Would you be interested in archiving this project and redirecting folks to https://github.com/nasa/python_cmr instead?

**Comment by KMarkert** [comment]
Thanks for the suggestion! I updated the readme with the following commit [219084e](https://github.com/KMarkert/simple-cmr/commit/219084e7b1825533464d3b1badd0614e55926cc8). Please feel free to reopen this issue and comment if you think the language should be updated. I will archive in two weeks to allow for you to comment, if I don't hear anything I will just go ahead and archive.
